### ISSUE TITLE
Could you provide the csv files?

### ISSUE THREAD

**Issue by erobic** [kohpangwei/group_DRO#1]
Hi, 

Could you provide these files?
- `list_attr_celeba.csv`
- `list_eval_partition.csv`

It would be easier to just use what you already have, instead of converting them on my own.

Edit:
For now, I will be using these:
https://raw.githubusercontent.com/togheppi/cDCGAN/master/list_attr_celeba.csv
https://raw.githubusercontent.com/Golbstein/keras-face-recognition/master/list_eval_partition.csv

You could just close this issue.

**Comment by kohpangwei** [comment]
Sorry for the late reply. We used the csv files from here: https://www.kaggle.com/jessicali9530/celeba-dataset. We've updated the README accordingly. Thanks for the catch!
