### ISSUE TITLE
not being able to reproduce your results on MNLI

### ISSUE THREAD

**Issue by ghost** [kohpangwei/group_DRO#2]
Hi
With the command in repo for MNLI, I am not able to reproduce your results.
Could you send me the command which reproduce your best results on MNLI?
Basically seems some argument are missing from that command. thanks.

**Comment by rc19** [comment]
Try this
python run_expt.py -s confounder -d MultiNLI -t gold_label_random -c sentence2_has_negation --fraction 1.0 --lr 2e-05 --batch_size 32 --weight_decay 0 --model bert --n_epochs 20

**Comment by ssagawa** [comment]
To replicate our ERM results, please run "python run_expt.py -s confounder -d MultiNLI -t gold_label_random -c sentence2_has_negation --lr 2e-05 --batch_size 32 --weight_decay 0 --model bert --n_epochs 20" as Chetanya suggests. To run group DRO, please add these flags: "--reweight_groups --robust --generalization_adjustment 0." Thanks Julia for the catch and Chetanya for chiming in! We've updated the README to include the group DRO command.
