### ISSUE TITLE
not being able to reproduce your results on CUB and CelebA

### ISSUE THREAD

**Issue by linyongver** [kohpangwei/group_DRO#4]
With the command in repo for MNLI, I am not able to reproduce your results.
Could you send me the command which reproduce your best results on CUB and CeleBA?
Especially for that with Large Weight Decay and Early stop
Thanks a lot.

**Comment by kohpangwei** [comment]
Hi! We provide sample commands for CUB and CelebA in the README as well (in addition to the command for MNLI). For the exact commands used in our experiments, please see 
https://worksheets.codalab.org/worksheets/0x621811fe446b49bb818293bae2ef88c0

**Comment by linyongver** [comment]
Thanks
