### ISSUE TITLE
Where is the random group chosen?

### ISSUE THREAD

**Issue by chanshing** [kohpangwei/group_DRO#7]
First, thanks for the nice work!
In your paper you show the following:
![image](https://user-images.githubusercontent.com/5551642/128641009-ffe9ff11-302b-4ed6-b976-6aaad1917e96.png)

I am having difficulty trying to find the part in your code corresponding to randomly picking a group: g~Uniform(1,...m)
Please could you tell me where can I find it?

**Comment by kohpangwei** [comment]
Hello! We reweight all the training examples so that it's equally likely to pick a point from each group here: https://github.com/kohpangwei/group_DRO/blob/master/data/dro_dataset.py#L52

Hope that helps!

**Comment by chanshing** [comment]
Thanks for the quick reply @kohpangwei
In that case, each batch may contain many groups? From the algorithm described in the paper, I thought that we had to sample only **one** group in each batch.

![image](https://user-images.githubusercontent.com/5551642/128700280-ff118581-f35e-422f-84ad-98149498e692.png)

**Comment by kohpangwei** [comment]
That's right, each batch may contain many groups. Sorry for the confusion! This is what we were referring to in Section 5 of the paper with 

> Concretely, we interleave SGD on θ and exponentiated gradient ascent on q (Algorithm 1). In practice, we use minibatches and a momentum term for θ; see Appendix C.2 for details.) 

We wrote the single-example case in Algorithm 1 to make the core idea clearer and avoid too much notation, but in practice we do batch updates.
