### ISSUE TITLE
Invalid link

### ISSUE THREAD

**Issue by Newbeeer** [kohpangwei/group_DRO#8]
Hi,

I cannot open the link that you provide (https://nlp.stanford.edu/data/dro/waterbird_complete95_forest2water2.tar.gz)  for waterbird dataset. Could you create a new link to access the dataset? Thanks a lot!

**Comment by ssagawa** [comment]
Hello! Our cluster (where the file is hosted) was down last night, but if you try again, it should work. Alternatively, we've included the same Waterbirds dataset in the WILDS package (which also has group DRO implemented), so you can also try it out there: https://github.com/p-lambda/wilds
Hope that helps!
