### ISSUE TITLE
Algorithm in paper and random groups per batch

### ISSUE THREAD

**Issue by chanshing** [kohpangwei/group_DRO#9]
Following up on previous question https://github.com/kohpangwei/group_DRO/issues/7
Please can you clarify whether we need to sample only *one* group at each iteration or it is OK to have multiple groups in a batch? In your algorithm, it seems to say that we need to sample only one group at each iteration, but this doesn't seem to be the case in the code.

![image](https://user-images.githubusercontent.com/5551642/128933469-81efbd9f-c427-485c-9a2e-4ff06485901f.png)

Additionally, please can you comment on the following remark from this paper https://arxiv.org/abs/2010.12230 ?

![image](https://user-images.githubusercontent.com/5551642/128933227-200c2c71-94c7-4063-a80c-d25c273189fe.png)

Is this remark justified?

**Comment by kohpangwei** [comment]
Yup! Copy-pasting from #7,

That's right, each batch may contain many groups. Sorry for the confusion! This is what we were referring to in Section 5 of the paper with

Concretely, we interleave SGD on θ and exponentiated gradient ascent on q (Algorithm 1). In practice, we use minibatches and a momentum term for θ; see Appendix C.2 for details.)

We wrote the single-example case in Algorithm 1 to make the core idea clearer and avoid too much notation, but in practice we do batch updates.

---

Hmm, regarding that comment, I don't think it's justified. Our algorithm uses a generic data loader. We'll contact the authors of that paper. Thanks for letting us know!
